#!url=https://raw.githubusercontent.com/Yumega/iLab/refs/heads/master/ios/VPN/SDR/module/CaiyunSVIP.module
#!name=彩云SVIP
#!desc=彩云SVIP

[Rule]
DOMAIN,gather.colorfulclouds.net,REJECT

[Script]
# 广告净化/弹窗AD/去除亲友卡/去除悬浮模块
caiyuntianqi = type=http-response, pattern=^https?:\/\/(ad|biz|wrapper|starplucker)\.cyapi\.cn\/.+\/((activity\?app_name|operation|config|req\?app_name=weather)|v\d\/(trial_card\/info|entries|friend_cards|token\/device)), script-path=https://raw.githubusercontent.com/Yumega/iLab/refs/heads/master/ios/VPN/SDR/js/caiyuntianqi.js, requires-body=true, max-size=-1, timeout=60

# VIP信息
caiyuntianqi = type=http-response, pattern=^https?:\/\/(biz|wrapper|starplucker)\.cyapi\.cn\/(v\d\/user\?app_name|.+\/v\d\/(vip_info|user_detail)), script-path=https://raw.githubusercontent.com/Yumega/iLab/refs/heads/master/ios/VPN/SDR/js/caiyuntianqi.js, requires-body=true, max-size=-1, timeout=60

# SVIP地图-48小时预报
caiyuntianqi = type=http-request, pattern=^https?:\/\/(api|wrapper)\.cyapi\.cn\/v\d\/(satellite|nafp\/origin_images), script-path=https://raw.githubusercontent.com/Yumega/iLab/refs/heads/master/ios/VPN/SDR/js/caiyuntianqi.js, timeout=60

[MITM]
hostname = %APPEND% *.cyapi.cn
