#!name=Spotify
#!desc=Spotify

[Script]
spotify-qx-header = type=http-request, pattern=^https?:\/\/[a-zA-Z0-9._-]+\.spotify\.com(:\d+)?\/user-customization-service\/v\d\/customize$, script-path=https://raw.githubusercontent.com/Yumega/iLab/refs/heads/master/ios/VPN/SDR/js/spotify-qx-header.js, timeout=60

spotify-proto = type=http-response, pattern=^https?:\/\/[a-zA-Z0-9._-]+\.spotify\.com(:\d+)?\/(bootstrap\/v\d\/bootstrap|user-customization-service\/v1\/customize)$, script-path=https://raw.githubusercontent.com/Yumega/iLab/refs/heads/master/ios/VPN/SDR/js/spotify-proto.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60

spotify-json = type=http-request, pattern=^https?:\/\/[a-zA-Z0-9._-]+\.spotify\.com(:\d+)?\/(artistview\/v\d\/artist|album-entity-view\/v2\/album)\/, script-path=https://raw.githubusercontent.com/Yumega/iLab/refs/heads/master/ios/VPN/SDR/js/spotify-json.js, timeout=60

[MITM]
hostname = %APPEND% *.spotify.com
