#!name=百度贴吧
#!desc=去广告

[Script]
tieba-json = type=http-response, pattern=^http(s:\/\/tiebac|:\/\/c\.tieba)\.baidu\.com\/(c\/f\/(frs\/(page|threadlist|generalTabList)|pb\/page|excellent\/personalized)$|tiebaads\/commonbatch|c\/s\/sync$), script-path=https://raw.githubusercontent.com/Yumega/iLab/refs/heads/master/ios/VPN/SDR/js/tieba-json.js, requires-body=true, max-size=-1, timeout=60

tieba-proto = type=http-response, pattern=^http(s:\/\/tiebac|:\/\/c\.tieba)\.baidu\.com\/c\/f\/(frs\/(page|threadlist|generalTabList)|pb\/page|excellent\/personalized)\?cmd, script-path=https://raw.githubusercontent.com/Yumega/iLab/refs/heads/master/ios/VPN/SDR/js/tieba-proto.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60

[MITM]
hostname = %APPEND% tiebac.baidu.com

